### PR TITLE
scour: Fix another variant of the crash from #260

### PR DESCRIPTION
**Pull request by nthykier**

### CODE REVIEW

**Comment by dmedvinsky** [comment]
Any plans on merging this?

**Comment by Ede123** [comment]
Thanks for the fix Nils and sorry for the delayed review!

I believe the important thing here is to avoid attempting to modify the list directly and remember to use `xml.dom`, methods like `appendChild` or `removeChild`.

With this in mind, I assume we can avoid cloning said nodes only to discard the originals later. A simple `appendChild` should be enough (it even removes the node from the original parent for us as as [per documentation](https://docs.python.org/3/library/xml.dom.html#xml.dom.Node.appendChild))

Would you be willing to give this approach another try before I merge this @nthykier ?

**Comment by nthykier** [comment]
@Ede123: Rebased.

**Comment by Ede123** [comment]
Thanks a lot!

**Pull request merged**
