### PR TITLE
Correct handling of "m0 0" vs. "z" commands

### PR DESCRIPTION
**Pull request by nthykier**
As observed in #163, scour sometimes do some unsafe path rewrites.

This branch solves that issue by separating the logic for removing path segments from the logic for rewriting commands.  The first commit removes the current unsafe optimization and the next one reimplements it (and adds a few more test cases for path cleaning of commands).

### CODE REVIEW

**Comment by oberstet** [comment]
@nthykier I had a quick look at the code, but obviously, I would need to dig deep into actual SVG specification to verify;) However, obviously it addresses a real issue. So maybe we could "reduce the risk" of this change (because it touches deep internals) by adding more test cases/files? That would make me feel comfortable merging. @Ede123 ? I think adding more test cases / files, in _both_ synthetic and real-world would be very good also in general ..

**Comment by Ede123** [comment]
I looked into this before and it looks mostly fine, although I wanted to double-check again before merging. It's certainly on the short-list for the next release.

Code-wise it's seems fine, although the new logic following `# remove no-op commands` is a bit hard to dig through - it might be an indication we can do even better - it might just be the spec that makes it unnecessarily complicated.

**Comment by oberstet** [comment]
@Ede123 sounds good! 

> note: I have split out my "idea" above of adding a set of real world docs in CI as a new issue https://github.com/scour-project/scour/issues/194 for discussion

**Comment by nthykier** [comment]
Eduard Braun:
> I looked into this before and it looks mostly fine, although I wanted to double-check again before merging. It's certainly on the short-list for the next release.
> 
> Code-wise it's seems fine, although the new logic following `# remove no-op commands` is a bit hard to dig through - it might be an indication we can do even better - it might just be the spec that makes it unnecessarily complicated.
> 

I am open to suggestions for improving the flow.  Please let me know if
there is anything concrete that makes it difficult for you to follow the
flow of the code.


The optimizations at a high level:

 * We can only remove "z" if the "pen" is at the same position as the
   start of the path (base case "m0 0z", but theoretically you can have
   steps in between "mX Y" and "z" as long as "z").

 * We can only rewrite m0 0 X Y to lX Y if 1) there is no "z" following
   the "m", OR 2) there is an "m" between this "m" and the "z".
   - This is because "z" is "relative" to the latest "m" before it.
   - Note that you can have multiple "z" cmds after the same "m"
     (a la: "m0 0 10 10-10-10 z l 10-10-10 10 z")

 * We want to remove redundant "m0 0" at the end of the path (e.g.
   because we optimized out a trailing "z").

In my code, I have used a "reverse iteration" (i.e. start at the end of
the path and move towards the start).  This has the advantage that we
can optimize path nodes immediately when we see them (assuming the
conditions are right).
  In a forward iteration, you find a node and have to look forward
because you can determine whether you can delete it.

Thanks,
~Niels

**Comment by nthykier** [comment]
Hi @Ede123,

Would you prefer if we simply disabled the removal of "z"-segments (i.e. the reduce this pull request to the first commit only)?  This would ensure that scour does not corrupt the images while avoid the code flow that you are not happy with.

**Comment by oberstet** [comment]
@nthykier just a quick note (to this and your other PRs): your work is welcome and much appreciated! I just find the time currently to dive into and review. we'll get it review and merged;)

**Comment by Ede123** [comment]
OK, finally got around to finish my review and we're good to go (sorry for the delay...).

I'm still not sure wether there's a better way to do this, but your version works @nthykier, so let's go with it and thank you very much for all the effort again! As @oberstet already noted it's much appreciated!

**Comment by nthykier** [comment]
Thanks for the review and merge. :)

**Pull request merged**
